version: '2'

services:

  wordpress:
    image: pattonwebz/wordpress-php7-1-apache-memcached
    container_name: wordpress_${WP_ID}
    hostname: ${WP_HOST}
    ports:
      - 80
    environment:

      WORDPRESS_DB_USER: database
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: wp_database
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DB_HOST: ${MYSQL_SUFFIX}:3306
      VIRTUAL_HOST: ${WP_HOST}
#     VIRTUAL_PROTO: https
      LETSENCRYPT_HOST: ${WP_HOST}
      LETSENCRYPT_EMAIL: user@example.com
    volumes:
      - data_volume:/var/www/html
      - ./${WP_ID}/home/wp:/home/wp
    links:
      - mysql:${MYSQL_SUFFIX}

  mysql:
    image: mariadb
    container_name: mariadb_${WP_ID}
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: wp_database
      MYSQL_USER: database
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./home/db:/home/db

  wp:
    image: pattonwebz/docker-wpcli
    container_name: wp_cli_${WP_ID}
    volumes_from:
      - wordpress
    links:
      - mysql:${MYSQL_SUFFIX}
    entrypoint: wp
    command: "--info"

volumes:
    db_data:
    data_volume:

networks:
  default:
    external:
      name: nginx-proxy

