version: '2'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./:/etc/nginx/conf.d
      - ./:/etc/nginx/vhost.d
    environment:
      - DEFAULT_HOST=wp1.stoat.xyz

networks:
  default:
    external:
      name: nginx-proxy
